baseurl = "https://whiletruelearn.github.io/"
title =  "whiletruelearn"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false


  [[params.navlinks]]
  name = "essays"
  url = "essays/"

  [[params.navlinks]]
  name = "projects"
  url = "projects/"

  [[params.navlinks]]
  name = "stories"
  url = "stories/"

